import { SideNav } from "./components/side-nav/side-nav";
import "./globals.css";
import { Roboto_Serif } from "next/font/google";

const font = Roboto_Serif({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <SideNav />
        {children}
      </body>
    </html>
  );
}
